### PR TITLE
Validation codes from wiki

### LINKED ISSUE #433: Move error codes from wiki into main git repo, with versioning
Move content from the wiki https://github.com/OCFL/spec/wiki/OCFL-Validator-Codes into the main git repo, under the `draft` directory so that it will then be versioned as we version the spec

### PR DESCRIPTION
**Pull request by zimeon**
Fixes #433 

I imagine we'll link to the rendered page on github from wiki and other places

### CODE REVIEW

**Comment by zimeon** [comment]
Currently rendered in branch as https://github.com/OCFL/spec/blob/issue-433/validation/validation-codes.md

**Comment by julianmorley** [comment]
The codes in my validator are here:
https://github.com/sul-dlss-labs/OCFL-Tools/blob/master/results_codes.md
There's some overlap, and some drift. I've been working on a way to better align these to actual checks but it's slow going.

**Comment by zimeon** [comment]
@julianmorley I have a similar issue. My plan is just to move my error codes out of the range of the canonical ones and align as I can

**Comment by julianmorley** [comment]
Approving this just to get a stake in the ground.

**Pull request merged**
