### PR TITLE
WIP DNM: Sample Notes for var implementation

### LINKED ISSUE #373: Clarify whether and OCFL Object Root may contain other files/directories not specified
By my reading of [3. OCFL Object](https://ocfl.io/0.3/spec/#object-spec) it is not clear whether  files or directories not specified in section 3 (conformance decl., version dirs, inventory, inventory checksum, logs dir) are permitted. I think we should add language to [3.1 Object Structure](https://ocfl.io/0.3/spec/#object-structure) along the lines of either:

> The OCFL Object Root MUST NOT contain files or directories other than those specified in the following sections.

or:

> The OCFL Object Root MAY contain additional files or directories not specified in the following sections. OCFL-compliant tools (including any validators) MUST ignore and such additional files or directories.

(or one could allow just files, or just directories)

### PR DESCRIPTION
**Pull request by neilsjefferies**
Assuming var is acceptable, this is a quick example of some relevant IN's. Fixes #373 and possibly #370

### CODE REVIEW

**Comment by zimeon** [comment]
In additional to making a decision on the underlying issue of whether we want to include the possibility of a `var` directory (#373), I think we need to have a discussion of how we talk about content in a `var` directory. My sense is that it may be dangerous to talk about it as a version, even and unmerged one. One might be able to use language around unmerged or uncommitted content that is can be described using a similar inventory structure to facilitate creation of a new version... or some such. But in OCFL terms it isn't an [OCFL Version](https://ocfl.io/draft/spec/#dfn-ocfl-version).

**Comment by awoods** [comment]
@zimeon : Do you believe @neilsjefferies' language in this PR is tied too closely with "OCFL Versions"?

**Comment by zimeon** [comment]
@awoods: yes, e.g. _"Mutable head objects have a current version"_

**Comment by neilsjefferies** [comment]
Not needed now we have extensions mechanism

**Pull request closed without merging**
