### PR TITLE
Release Alpha 0.1

### PR DESCRIPTION
**Pull request by awoods**
Resolves: https://github.com/OCFL/spec/issues/238

### CODE REVIEW

**Comment by julianmorley** [comment]
I think the alpha is good to go, but I can't review a reverted PR...

**Comment by ahankinson** [comment]
I think the idea is that we'll revert it if you have a problem, which you can signal with a thumbs-down

**Comment by zimeon** [comment]
@neilsjefferies -- just waiting for your post-merge :+1: on this... (comment not review as that is all github allows post-merge)

**Comment by julianmorley** [comment]
+1 from me.

**Pull request merged**
