### PR TITLE
Big Implementation Notes edit

### PR DESCRIPTION
**Pull request by neilsjefferies**
May collide with Rosy's updates

### CODE REVIEW

**Comment by rosy1280** [comment]
yikes @neilsjefferies it looks like this conflicts with #172 

if you want i can try to incorporate in your additions for storage root hierarchy and basic file operations.  it also looks like you moved sections around so i can attempt to do that too.

**Comment by neilsjefferies** [comment]
Feel free, I was going to merge yours and then do that anyway but I have 
to feed family etc just at the moment!
I haven't moved sections around but the insertions were big enough to 
throw the diff's off. The Filesystem hierarchy and the basic operations 
are the big additions.

Neil

**Comment by rosy1280** [comment]
I found it too hard to fix the collisions here.  I went through and made the updates by hand in a new branch.  @neilsjefferies if #179 looks good to you, then we can close this PR.

**Comment by neilsjefferies** [comment]
Looks good, I've approved and merged. Thanks!

Neil

**Pull request closed without merging**
