### PR TITLE
Clarify non-ordered nature of version items in inventory

### PR DESCRIPTION
**Pull request by awoods**
Resolves: https://github.com/OCFL/spec/issues/218

### CODE REVIEW

**Comment by ahankinson** [comment]
It would probably be helpful to explain why ( version directories are already ordered) since a JSON array is an ordered data structure.

**Comment by zimeon** [comment]
This issue does beg the question of whether there should be a hash of versions indexed by the version directory:

```
"head": "v2",      
"versions": {
  "v1": { ...stuff for v1... },
  "v2": { ...stuff for v2...}
}
```

did we talk about that?

**Comment by ahankinson** [comment]
No, we didn't talk about that. I would be fine with this solution as well. It would also make it easy to say that the value of `head` must be a key in the versions object.

**Comment by zimeon** [comment]
I'm going to bounce the question above up to an issue

**Pull request merged**
