### PR TITLE
Add definition of "Registered Extension Name"

### PR DESCRIPTION
**Pull request by awoods**
Resolves: https://github.com/OCFL/spec/issues/486

### CODE REVIEW

**Comment by ahankinson** [comment]
I note that @zimeon's comment on #486 says:

> The Registered Name of an extension is the name of the extension file in the docs directory, excluding the .md extension.

But it looks like the files also have a leading number? Is that part of the name too?

**Comment by awoods** [comment]
@ahankinson : I think it is most clear if we use the "Extension Name" documented in the actual extension:
https://github.com/OCFL/extensions/pull/19/files#diff-10a1d32f04789570466246d3a20c4b6bR3

**Comment by ahankinson** [comment]
So that does include the leading numbers. OK.

**Comment by zimeon** [comment]
I think the numbers are part of it. I think this will all become very obvious when we have the **Extension Name: 1234-some-name** at the top of each extension

**Pull request merged**
